version: "3"

services:
  flowcli:
    container_name: flowcli
    build:
      context: ./
      dockerfile: flowcli.dockerfile
    volumes:
      - ./:/dapp
    ports:
      - "3596:3596"
      - "8092:8080"